// ReactTs/src/components/Chatbot/Chatbot.tsx
import React, { ReactElement, useCallback, useEffect, useRef, useState } from 'react';
import { Subscription } from 'rxjs';

import 'src/components/Chatbot/Chatbot.scss';
import RappidService from 'src/services/rappid.service';
import JsonEditor from 'src/components/Chatbot/JsonEditor/JsonEditor';
import Inspector from 'src/components/Chatbot/Inspector/Inspector';
import EventBusServiceContext from 'src/services/event-bus-service.context';
import { EventBusService } from 'src/services/event-bus.service';
import { SharedEvents } from 'src/rappid/controller';
import { importGraphFromJSON, loadStencilShapes, zoomToFit } from 'src/rappid/actions';
import { STENCIL_WIDTH } from 'src/theme';

import exampleGraphJSON from 'src/rappid/config/example-graph.json';

const Chatbot = (): ReactElement => {

    const elementRef = useRef(null);
    const toolbarRef = useRef(null);
    const stencilRef = useRef(null);
    const paperRef = useRef(null);

    const [rappid, setRappid] = useState(null);
    const [eventBusService] = useState(new EventBusService());
    const [stencilOpened, setStencilOpened] = useState(true);
    const [jsonEditorOpened, setJsonEditorOpened] = useState(true);
    const [fileJSON, setFileJSON] = useState(null);
    const [subscriptions] = useState(new Subscription());

    const openFile = useCallback((json: Object): void => {
        setFileJSON(json);
        importGraphFromJSON(rappid, json);
        zoomToFit(rappid);
    }, [rappid]);

    const onStart = useCallback((): void => {
        loadStencilShapes(rappid);
        openFile(exampleGraphJSON);
    }, [rappid, openFile]);

    const onJsonEditorChange = useCallback((json: Object): void => {
        if (rappid) {
            importGraphFromJSON(rappid, json);
        }
    }, [rappid]);

    const onRappidGraphChange = useCallback((json: Object): void => {
        setFileJSON(json);
    }, []);

    const onStencilToggle = useCallback((): void => {
        if (!rappid) {
            return;
        }
        const { scroller, stencil } = rappid;
        if (stencilOpened) {
            stencil.unfreeze();
            scroller.el.scrollLeft += STENCIL_WIDTH;
        } else {
            stencil.freeze();
            scroller.el.scrollLeft -= STENCIL_WIDTH;
        }
    }, [rappid, stencilOpened]);

    const toggleJsonEditor = (): void => {
        setJsonEditorOpened(!jsonEditorOpened);
    };

    const toggleStencil = (): void => {
        setStencilOpened(!stencilOpened);
    };

    useEffect((): void => {
        onStencilToggle();
    }, [stencilOpened, onStencilToggle]);

    const setStencilContainerSize = useCallback((): void => {
        stencilRef.current.style.width = `${STENCIL_WIDTH}px`;
    }, []);

    useEffect(() => {
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.GRAPH_CHANGED, (json: Object) => onRappidGraphChange(json))
        );
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.JSON_EDITOR_CHANGED, (json: Object) => onJsonEditorChange(json))
        );
    }, [eventBusService, subscriptions, onRappidGraphChange, onJsonEditorChange]);

    useEffect(() => {
        setRappid(new RappidService(
            elementRef.current,
            paperRef.current,
            stencilRef.current,
            toolbarRef.current,
            eventBusService
        ));
    }, [eventBusService]);

    useEffect(() => {
        if (!rappid) {
            return;
        }
        setStencilContainerSize();
        onStart();
    }, [rappid, onStart, setStencilContainerSize]);

    useEffect(() => {
        if (!rappid) {
            return;
        }
        return () => {
            subscriptions.unsubscribe();
            rappid.destroy();
        };
    }, [rappid, subscriptions]);

    return (
        <EventBusServiceContext.Provider value={eventBusService}>
            <div ref={elementRef} className="rappid-scope chatbot">
                <div ref={toolbarRef}/>
                <div className="side-bar">
                    <div className="toggle-bar">
                        <div onClick={toggleStencil}
                             className={'icon toggle-stencil ' + (!stencilOpened ? 'disabled-icon' : '')}
                             data-tooltip="Toggle Element Palette"
                             data-tooltip-position-selector=".toggle-bar"/>
                        <div onClick={toggleJsonEditor}
                             className={'icon toggle-editor ' + (!jsonEditorOpened ? 'disabled-icon' : '')}
                             data-tooltip="Toggle JSON Editor"
                             data-tooltip-position-selector=".toggle-bar"/>
                    </div>
                    <div ref={stencilRef}
                         style={{ display: stencilOpened ? 'initial' : 'none' }}
                         className="stencil-container"/>
                </div>
                <div className="main-container">
                    <div ref={paperRef} className="paper-container"/>
                    <div style={{ display: jsonEditorOpened ? 'initial' : 'none' }}>
                        <JsonEditor content={fileJSON}/>
                    </div>
                </div>
                <Inspector/>
            </div>
           
        </EventBusServiceContext.Provider>
    );
};

export default Chatbot;

// tempy/rappid/apps/Chatbot/Angular16/src/app/chatbot/chatbot.component.ts
/*! JointJS+ v3.7.3 - HTML5 Diagramming Framework - TRIAL VERSION

Copyright (c) 2023 client IO

 2024-02-02 


This Source Code Form is subject to the terms of the JointJS+ Trial License
, v. 2.0. If a copy of the JointJS+ License was not distributed with this
file, You can obtain one at https://www.jointjs.com/license
 or from the JointJS+ archive as was distributed by client IO. See the LICENSE file.*/


import {
    AfterViewInit,
    ChangeDetectorRef,
    Component,
    ElementRef,
    OnDestroy,
    OnInit,
    Renderer2,
    ViewChild,
    ViewEncapsulation
} from '@angular/core';
import { Subscription } from 'rxjs';

import RappidService from 'src/services/rappid.service';
import { EventBusService } from 'src/services/event-bus.service';
import { STENCIL_WIDTH } from 'src/theme';
import { SharedEvents } from 'src/rappid/controller';
import { loadStencilShapes, importGraphFromJSON, zoomToFit } from 'src/rappid/actions';

import exampleGraphJSON from 'src/rappid/config/example-graph.json';

@Component({
    selector: 'chatbot',
    templateUrl: './chatbot.component.html',
    styleUrls: ['./chatbot.component.scss'],
    host: { class: 'rappid-scope' },
    encapsulation: ViewEncapsulation.None
})

export class ChatbotComponent implements AfterViewInit, OnInit, OnDestroy {

    @ViewChild('paper') paper: ElementRef;
    @ViewChild('stencil') stencil: ElementRef;
    @ViewChild('toolbar') toolbar: ElementRef;

    public rappid: RappidService;
    public stencilOpened = true;
    public jsonEditorOpened = true;
    public fileJSON: object;

    private subscriptions = new Subscription();

    constructor(private element: ElementRef,
                private eventBusService: EventBusService,
                private cdr: ChangeDetectorRef,
                private renderer: Renderer2) {
    }

    public ngOnInit(): void {
        const { subscriptions, eventBusService } = this;
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.GRAPH_CHANGED, (json: object) => this.onRappidGraphChange(json))
        );
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.JSON_EDITOR_CHANGED, (json: object) => this.onJsonEditorChange(json))
        );
    }

    public ngAfterViewInit(): void {
        const { element, paper, stencil, toolbar, eventBusService, cdr } = this;
        this.rappid = new RappidService(
            element.nativeElement,
            paper.nativeElement,
            stencil.nativeElement,
            toolbar.nativeElement,
            eventBusService,
        );
        this.setStencilContainerSize();
        this.onStart();
        cdr.detectChanges();
    }

    public ngOnDestroy(): void {
        this.subscriptions.unsubscribe();
        this.rappid.destroy();
    }

    public openFile(json: object): void {
        const { rappid } = this;
        this.fileJSON = json;
        importGraphFromJSON(rappid, json);
        zoomToFit(rappid);
    }

    public toggleJsonEditor(): void {
        this.jsonEditorOpened = !this.jsonEditorOpened;
    }

    public toggleStencil(): void {
        this.stencilOpened = !this.stencilOpened;
        this.onStencilToggle();
    }

    private onStart(): void {
        const { rappid } = this;
        loadStencilShapes(rappid);
        this.openFile(exampleGraphJSON);
    }

    private onJsonEditorChange(json: object): void {
        const { rappid } = this;
        if (rappid) { importGraphFromJSON(rappid, json); }
    }

    private onRappidGraphChange(json: object): void {
        this.fileJSON = json;
    }

    private setStencilContainerSize(): void {
        const { renderer, stencil } = this;
        renderer.setStyle(stencil.nativeElement, 'width', `${STENCIL_WIDTH}px`);
        this.onStencilToggle();
    }

    private onStencilToggle(): void {
        const { rappid, stencilOpened } = this;
        const { scroller, stencil } = rappid;
        if (stencilOpened) {
            stencil.unfreeze();
            scroller.el.scrollLeft += STENCIL_WIDTH;
        } else {
            stencil.freeze();
            scroller.el.scrollLeft -= STENCIL_WIDTH;
        }
    }
}
