// tempy/rappid/apps/Chatbot/Angular16/src/app/json-editor/json-editor.component.ts
/*! JointJS+ v3.7.3 - HTML5 Diagramming Framework - TRIAL VERSION

Copyright (c) 2023 client IO

 2024-02-02 


This Source Code Form is subject to the terms of the JointJS+ Trial License
, v. 2.0. If a copy of the JointJS+ License was not distributed with this
file, You can obtain one at https://www.jointjs.com/license
 or from the JointJS+ archive as was distributed by client IO. See the LICENSE file.*/


import { Component, OnInit, Input } from '@angular/core';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

import { EventBusService } from 'src/services/event-bus.service';
import { SharedEvents } from 'src/rappid/controller';

const DEBOUNCE_TIME_MS = 500;

@Component({
    selector: 'chatbot-json-editor',
    templateUrl: './json-editor.component.html',
    styleUrls: ['./json-editor.component.scss']
})
export class JsonEditorComponent implements OnInit {

    @Input() content: object;
    public placeholder = 'e.g. { "cells": [{ "type": "app.Message"}] }';
    public contentSubject = new Subject<object>();

    constructor(private eventBusService: EventBusService) {
    }

    public ngOnInit(): void {
        const { contentSubject, eventBusService } = this;
        contentSubject.pipe(debounceTime(DEBOUNCE_TIME_MS)).subscribe((json: object) => {
            eventBusService.emit(SharedEvents.JSON_EDITOR_CHANGED, json);
        });
    }

    public parseJSON(jsonString: string): void {
        const { contentSubject } = this;
        let json;
        if (!jsonString) {
            json = { cells: [] };
        } else {
            try {
                json = JSON.parse(jsonString);
            } catch (e) {
                // Invalid JSON
                return;
            }
        }
        contentSubject.next(json);
    }
}

// ReactTs/src/components/Chatbot/JsonEditor/JsonEditor.tsx
import React, { ReactElement, useContext, useEffect, useState } from 'react';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

import 'src/components/Chatbot/JsonEditor/JsonEditor.scss';
import eventBusServiceContext from 'src/services/event-bus-service.context';
import { SharedEvents } from 'src/rappid/controller';

interface Props {
    content: Object;
}

const DEBOUNCE_TIME_MS = 500;

const JsonEditor = (props: Props): ReactElement => {

    const [placeholder] = useState('e.g. { "cells": [{ "type": "app.Message"}] }');
    const [content, setContent] = useState<string | Object>(null);
    console.log(content);
    const [contentSubject] = useState(new Subject<Object>());
    const eventBusService = useContext(eventBusServiceContext);

    useEffect(() => {
        contentSubject.pipe(debounceTime(DEBOUNCE_TIME_MS)).subscribe((json: Object) => {
            eventBusService.emit(SharedEvents.JSON_EDITOR_CHANGED, json);
        });
    }, [contentSubject, eventBusService]);

    useEffect(() => {
        if (props.content) {
            setContent(props.content);
        }
    }, [props.content]);

    const parseJSON = (jsonString: string): void => {
        setContent(jsonString);
        let json;
        if (!jsonString) {
            json = { cells: [] };
        } else {
            try {
                json = JSON.parse(jsonString);
            } catch (e) {
                // Invalid JSON
                return;
            }
        }
        contentSubject.next(json);
    };

    const formatJSON = (json: string | Object): string => {
        if (!json) {
            return '';
        }
        return typeof json === 'string' ? json : JSON.stringify(json, null, 2);
    };

    return (
        <div className="chatbot-json-editor">
            <textarea placeholder={placeholder}
                      spellCheck="false"
                      value={formatJSON(content)}
                      onChange={(e) => parseJSON(e.target.value)}
            />
        </div>
    );
};

export default JsonEditor;
